## Load image with software requirements for libnnpdf
image: zaharid/debian-7-devbase

stages:
    - build-deploy


#Set to "true" to generate builds for non-default branches
variables:
    UPLOAD_NON_MASTER: "true"
    CONDAPATH: "/root/miniconda3/"
    OUTPUT_ARCH: "linux-64"
    OUTPUT_CHANNEL: "conda-pkgs"

## Run the configure and make tests
job1:
    stage: build-deploy
    VARIABlES:
        CONDA_PY: "36"
    script: ".ciscripts/build-deploy2.sh conda-recipe"

    #We copy the conda package to the git path to be untracked and
    #then catch it as an "artifact"

    #TODO: Do two separate stages when we have a newer version with this
    # implemented (and there are proper docs on how to do it):
    # https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/2437
    #
    #
    #No idea why this doesn't work
    #artifacts:
    #    paths:
    #        - /yes/conda-bld/linux-64/

