package:
    name: asyncwatch
    version: "{{ GIT_DESCRIBE_TAG[1:] }}.{{ GIT_DESCRIBE_NUMBER }}"

source:
    git_url: ../

build:
    skip: True # [not py36]

requirements:
    build:
      - python
      - curio
      - setuptools
      - cffi
    run:
      - python
      - curio
      - cffi

test:
    requires:
        - pytest
        - coverage
    commands:
        - "py.test --pyargs asyncwatch"
