package:
    name: asyncwatch
    version: "{{ environ.get('GIT_DESCRIBE_TAG', '')[1:] }}.{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}"

source:
    git_url: ../

requirements:
    build:
      - python
      - curio
      - setuptools
      - cffi
    run:
      - python
      - curio
      - cffi

test:
    requires:
        - pytest
        - coverage
    commands:
        - "py.test --pyargs asyncwatch"
